-- food_log schema — migration 0001 (source of truth, see PLAN.md "Schema design")
-- Applied by `python -m app.migrate`. Everything lives in the food_log schema;
-- nothing outside it is ever touched (working agreement).

CREATE SCHEMA IF NOT EXISTS food_log;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS food_log.schema_migrations (
  filename   text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- Identity from day one, single user in v1 (decision 1). No credentials in v1;
-- the static API token maps to user 1 in code (get_current_user).
CREATE TABLE IF NOT EXISTS food_log.users (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO food_log.users (id, name)
  OVERRIDING SYSTEM VALUE
  VALUES (1, 'primary')
  ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('food_log.users', 'id'),
              (SELECT max(id) FROM food_log.users));

-- Global food catalog. Nutrition is always per-100g (nutrients table);
-- grams are the canonical logging unit.
CREATE TABLE IF NOT EXISTS food_log.foods (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  source         text NOT NULL CHECK (source IN
                   ('fdc_foundation', 'fdc_sr_legacy', 'fdc_branded', 'off', 'custom')),
  source_id      text NOT NULL,
  name           text NOT NULL,
  brand          text,
  barcode        text,
  search_vec     tsvector GENERATED ALWAYS AS
                   (to_tsvector('english', coalesce(name, '') || ' ' || coalesce(brand, ''))) STORED,
  source_payload jsonb,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source, source_id)
);

CREATE INDEX IF NOT EXISTS foods_search_idx  ON food_log.foods USING gin (search_vec);
CREATE INDEX IF NOT EXISTS foods_name_trgm_idx ON food_log.foods USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS foods_barcode_idx ON food_log.foods (barcode) WHERE barcode IS NOT NULL;

-- Raw grams is always available implicitly; rows here are the food's named portions.
CREATE TABLE IF NOT EXISTS food_log.portions (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  food_id     bigint NOT NULL REFERENCES food_log.foods(id) ON DELETE CASCADE,
  description text NOT NULL,
  gram_weight numeric NOT NULL CHECK (gram_weight > 0)
);

CREATE INDEX IF NOT EXISTS portions_food_idx ON food_log.portions (food_id);

-- Import EVERY nutrient the source reports, snake_cased keys (e.g. magnesium_mg),
-- normalized per-100g.
CREATE TABLE IF NOT EXISTS food_log.nutrients (
  food_id         bigint NOT NULL REFERENCES food_log.foods(id) ON DELETE CASCADE,
  nutrient_key    text NOT NULL,
  amount_per_100g numeric NOT NULL,
  PRIMARY KEY (food_id, nutrient_key)
);

-- One row per logged item. date is CLIENT-LOCAL (decision 2); no meal column
-- (decision 7). client_id makes outbox retries idempotent.
CREATE TABLE IF NOT EXISTS food_log.log_entries (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id      integer NOT NULL REFERENCES food_log.users(id),
  date         date NOT NULL,
  food_id      bigint NOT NULL REFERENCES food_log.foods(id),
  grams        numeric NOT NULL CHECK (grams > 0),
  portion_id   bigint REFERENCES food_log.portions(id) ON DELETE SET NULL,
  portion_qty  numeric CHECK (portion_qty > 0),
  logged_at    timestamptz NOT NULL DEFAULT now(),
  client_id    uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  entry_method text NOT NULL DEFAULT 'manual' CHECK (entry_method IN
                 ('manual', 'barcode', 'favorite', 'ai_photo', 'ai_text', 'mcp'))
);

CREATE INDEX IF NOT EXISTS log_entries_user_date_idx ON food_log.log_entries (user_id, date);

-- lbs in, lbs out (display unit is pounds everywhere).
CREATE TABLE IF NOT EXISTS food_log.body_weight (
  id        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id   integer NOT NULL REFERENCES food_log.users(id),
  date      date NOT NULL,
  weight_lb numeric NOT NULL CHECK (weight_lb > 0),
  logged_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, date)
);

-- Versioned by effective_date; current target = latest effective_date <= today.
-- sodium_mg is first-class (decision 8).
CREATE TABLE IF NOT EXISTS food_log.targets (
  user_id        integer NOT NULL REFERENCES food_log.users(id),
  effective_date date NOT NULL,
  kcal           numeric,
  protein_g      numeric,
  carbs_g        numeric,
  fat_g          numeric,
  fiber_g        numeric,
  sodium_mg      numeric,
  PRIMARY KEY (user_id, effective_date)
);

-- One tap logs the food at its usual amount (decision 10). Amount is either
-- raw grams or a portion reference — exactly one form must be present.
CREATE TABLE IF NOT EXISTS food_log.favorites (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL REFERENCES food_log.users(id),
  food_id       bigint NOT NULL REFERENCES food_log.foods(id) ON DELETE CASCADE,
  default_grams numeric CHECK (default_grams > 0),
  portion_id    bigint REFERENCES food_log.portions(id) ON DELETE CASCADE,
  portion_qty   numeric CHECK (portion_qty > 0),
  label         text,
  position      integer NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (default_grams IS NOT NULL AND portion_id IS NULL AND portion_qty IS NULL) OR
    (default_grams IS NULL AND portion_id IS NOT NULL AND portion_qty IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS favorites_user_idx ON food_log.favorites (user_id, position);
